# Generated by Django 4.1.3 on 2022-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('creted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
