# Generated by Django 4.1.3 on 2022-11-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
